CC=g++
CFLAGS=-Wall -O3

all: segment_tree sparse_table

segment_tree:
	$(CC) $(CFLAGS) segment_tree.cpp -o segment_tree

sparse_table:
	$(CC) $(CFLAGS) sparse_table.cpp -o sparse_table

clean:
	rm segment_tree sparse_table
