#!/usr/bin/env python

import itertools
import numpy
import matplotlib.pyplot as plot

sizes = [100, 500, 1000, 5000, 10000, 50000, 100000, 500000, 1000000]

results = {'segment_tree' : {'time' : [], 'size' : [], 'data' : []}, 'sparse_table' : {'time' : [], 'size' : [], 'data' : []}}

for (structure, size) in itertools.product(results.keys(), sizes):
    with open(structure + "_" + str(size)) as data_file:
        time = []
        size = []
        data = []
        for line in data_file:
            clauses = line.split(",")
            time.append(float(clauses[0]))
            size.append(int(clauses[1]))
            data.append(int(clauses[2]))
        results[structure]['time'].append(numpy.mean(time))
        results[structure]['size'].append(numpy.mean(size))
        results[structure]['data'].append(numpy.mean(data))

plot.figure()
plot.plot(sizes, results['segment_tree']['time'], 'r', sizes, results['sparse_table']['time'], 'b')
plot.xlabel('Size of Data')
plot.ylabel('Total Time (ms)')
plot.figure()
plot.plot(sizes, results['segment_tree']['size'], 'r', sizes, results['sparse_table']['size'], 'b')
plot.xlabel('Size of Data')
plot.ylabel('Total Size (MB)')
plot.figure()
plot.plot(sizes, results['segment_tree']['data'], 'r', sizes, results['sparse_table']['data'], 'b')
plot.xlabel('Size of Data')
plot.ylabel('Data/Stack Size (MB)')
plot.show()