#!/bin/bash
# Gathers profile data.
# Usage: './profile x'
# x (integer): The size of the lists to generate
# Example command: './profile 10000'

make profile

for i in {1..10}; do
    ./generate_list $1
    ./segment_tree $1 >> segment_tree_$1
    ./sparse_table $1 >> sparse_table_$1
    ./check_minimum $1
done

rm list queries answers segment_tree_results sparse_table_results

make clean
